language: php

php:
  - 7.0

env:
  global:
    - setup=basic

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: setup=lowest
    - php: 7.0
      env: setup=stable

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - sqlite3
  - memcached
  - redis-server

before_install:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - pecl install -f redis
  - travis_retry composer self-update

install:
  - travis_retry composer install --dev

script: vendor/bin/phpunit
